services:
  bot:
    build: .
    command: ./murkov
    env_file:
      - .env
    depends_on:
    - db
    container_name:
      murkov-bot
  db:
    container_name: murkov-db
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - ${PORT}:5432
    volumes:
      - ./postgres.db:/var/lib/postgresql/data