services:
  murkov:
    build:
      dockerfile: murkov/Dockerfile
      context: .
    env_file:
      - .env
    depends_on:
    - db
    container_name:
      murkov-bot
  db:
    container_name: slykbots-db
    image: postgres:15
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - ${PORT}:5432
    volumes:
      - ./db/postgres.db:/var/lib/postgresql/data