services:
  murkov:
    build:
      dockerfile: murkov/Dockerfile
      context: .
    env_file:
      - .env
    depends_on:
    - db
    container_name:
      murkov-bot
    restart: always
  rpp:
    build:
      dockerfile: rpp/Dockerfile
      context: .
    env_file:
      - .env
    depends_on:
      - db
    container_name:
      rpp-bot
    restart: always
  db:
    container_name: slykbots-db
    restart: always
    image: postgres:15
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - ${PORT}:5432
    volumes:
      - ./db/postgres.db:/var/lib/postgresql/data