services:
  bot:
    restart: always
    container_name: murkov-bot
    command:
      - ./murkov
    image: ghcr.io/slyk26/murkov:master
    env_file:
      - .env
    depends_on:
    - db
  db:
    restart: always
    container_name: murkov-db
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - ${PORT}:5432
    volumes:
      - ./postgres.db:/var/lib/postgresql/data