[package]
name = "shared"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
songbird = {version = "=0.3.2", features = ["yt-dlp", "builtin-queue"]}
serenity = "*"
log = "0.4.18"