name: Docker Image CI

on:
  push

jobs:
  build_and_publish:

    runs-on: ubuntu-latest
    env:
      DOCKER_TARGET_PLATFORM: linux/arm/v8

    steps:
    - uses: actions/checkout@v3
    - name: build and push the docker image
      run: |
        docker login --username slyk26 --password ${{ secrets.GH_PAT }} ghcr.io
        docker build . --tag ghcr.io/slyk26/murkov:latest
        docker push ghcr.io/slyk26/murkov:latest
