name: Docker Image CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pguyot/arm-runner-action@v2
        id: build_and_publish
        with:
          base_image: dietpi:rpi_armv8_bullseye
          commands: |
            apt install docker
            docker login --username slyk26 --password ${{ secrets.GH_PAT }} ghcr.io
            docker build . --tag ghcr.io/slyk26/murkov:latest --platform=linux/arm64/v8
            docker push ghcr.io/slyk26/murkov:latest