name: Docker Build/Publish Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE: slyk26/murkov
      DOCKER_USERNAME:  slyk26
      DOCKER_PASSWORD: ${{ secrets.GH_PAT }}
      DOCKER_TARGET_PLATFORM: linux/arm64/v8

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Prepare
        if: success()
        id: prepare
        run: |
          echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}        
          echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}        
          echo ::set-output name=version::${GITHUB_RUN_NUMBER}    

      - name: Docker Login
        if: success()
        run: docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"

      - name: Run Buildx (push image)
        if: success()
        run: docker buildx build --platform ${{ steps.prepare.outputs.docker_platform }} --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }} --file ./Dockerfile --output type=image,push=true .